### ISSUE TITLE
hovering over the top dropdown menus does not change color of selection

### ISSUE THREAD

**Issue by felipe1982** [bceskavich/dracula-at-night#4]
hovering over the top dropdown menus does not change color of selection.

I am hovering my mouse over **Open File...** but it does not change color. See image.

![2019-03-14 19_14_30-Extension_ Dracula At Night - advisor_sales - Visual Studio Code](https://user-images.githubusercontent.com/275621/54344842-8360c100-468d-11e9-959b-a93937bfab52.jpg)

**Comment by sargalias** [comment]
Worked on this in PR #5

**Comment by bceskavich** [comment]
@felipe1982 I'm closing this issue out, since as @sargalias mentioned this was addressed in #5. That fix was just now released in v2.6.0. If you're still seeing the issue, please let me know.
