### ISSUE TITLE
how do you change the background of command panel?

### ISSUE THREAD

**Issue by applemate** [bceskavich/dracula-at-night#6]
<img width="1400" alt="Screen_Shot_2019-07-20_at_11_33_31_PM" src="https://user-images.githubusercontent.com/538657/61581320-1a132200-ab47-11e9-8c83-5f23b551fc2d.png">

what the setting key for that? panel.background?

**Comment by bceskavich** [comment]
Yes it should be `panel.background`. You can see the full set of theme config options [here](https://code.visualstudio.com/api/references/theme-color).
