### ISSUE TITLE
How to change the text color in the editor ?

### ISSUE THREAD

**Issue by aditya1191** [bceskavich/dracula-at-night#8]
The text seems too bright i want to tone it down a bit !

**Comment by bceskavich** [comment]
@aditya1191 it should be `editor.foreground`. You can see the full set of theme config options [here](https://code.visualstudio.com/api/references/theme-color).

**Comment by Telokis** [comment]
@aditya1191 Did you manage to do it? I'm in the same situation, I think the text is too bright when compared to the background
