### ISSUE TITLE
Font of the README screenshot

### ISSUE THREAD

**Issue by martinjuhasz** [bceskavich/dracula-at-night#9]
Which font is the one you are using in the example screenshot in the README file?
Really digging that bold font with that theme, but i cannot seem to find that font anywhere.

Thanks!

<img width="891" alt="68747470733a2f2f647a776f6e73656d72697368372e636c6f756466726f6e742e6e65742f6974656d732f327133723135343332733348303030313375316a2f53637265656e25323053686f74253230323031382d30362d3032253230617425323031302e31362e30312e706e67" src="https://user-images.githubusercontent.com/204190/68781426-12b4de80-0638-11ea-9c89-42f1f628958c.png">

**Comment by bceskavich** [comment]
@martinjuhasz it's [Consolas](https://docs.microsoft.com/en-us/typography/font-list/consolas). I took this screenshot on macOS High Sierra with the `default` option set for VSCode's `Font Aliasing` setting.
